Models/DataContext.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System.IO;


namespace VT_POO3.Models
{
    public class DataContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder  optionsBuilder) 
        {
            var builder = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory()).AddJsonFile("appsettings.json");
            var configuration = builder.Build();
            optionsBuilder.UseMySql(configuration["ConnectionStrings:DefaultConnection"]);
        }
        public DbSet<Episodio> Episodios { get; set; }
        public DbSet<Serie> Series { get; set; }

    }
}

Models/Episodio.cs
using System.ComponentModel.DataAnnotations.Schema;


namespace VT_POO3.Models
{
    [Table("episodios")]
    public class Episodio
    {
        public string Id { get; set; }
        public string Nome { get; set; }
        public int Temporada { get; set; }
        public double Nota { get; set; }
    }

}

Models/ErrorViewModel.cs
using System;

namespace VT_POO3.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Serie.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace VT_POO3.Models
{
    [Table("series")]
    public class Serie
    {
        public string Id { get; set; }
        public string Nome { get; set; }
        public string Autor { get; set; }
        public string Criadora { get; set; }
    }
}

Controllers/AddController.cs
using Microsoft.AspNetCore.Mvc;

namespace VT_POO3.Controllers
{
    public class AddController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/EpisodioController.cs
using Microsoft.AspNetCore.Mvc;
using VT_POO3.Models;
using System.Linq;
using Microsoft.Extensions.Logging;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace VT_POO3.Controllers
{
  [Route("epsiodio")]
    public class EpisodioController : Controller
    {
    private readonly ILogger<EpisodioController> _logger;

    public EpisodioController(ILogger<EpisodioController> logger)
    {
        _logger = logger;
    }

        private DataContext db = new DataContext();
        
       [Route("episodio")]
       [Route("Index_2")]
      // [Route("~/")]

        public IActionResult Index_2()
        {
            ViewBag.episodios = db.Episodios.ToList();
            return View("Index_2");
        }


        [HttpGet]
        [Route("Add")]
        public IActionResult Add()
        { 
            return View("Add");
        }

        [HttpPost]
        [Route("Add")]
        public IActionResult Add(Episodio episodio)
        {
            db.Episodios.Add(episodio);
            db.SaveChanges();
            return RedirectToAction("Index_2");
        }

        [HttpGet]
        [Route("Delete/{id}")]
        public IActionResult Delete(string id)
        {
            db.Episodios.Remove(db.Episodios.Find(id));
            db.SaveChanges();
            return RedirectToAction("Index_2");
        }

        [HttpGet]
        [Route("Edite/{id}")]
        public IActionResult Edite(string id)
        {
            return View("Edite", db.Episodios.Find(id));
        }

        [HttpPost]
        [Route("Edite/{id}")]
        public IActionResult Edite(Episodio episodio)
        {
            db.Entry(episodio).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index_2");
        }
        public IActionResult Privacy()
        {
            return View();
        }

    }
}

Controllers/SerieController.cs
using Microsoft.AspNetCore.Mvc;
using VT_POO3.Models;
using System.Linq;
using Microsoft.Extensions.Logging;

namespace VT_POO3.Controllers
{
  [Route("serie")]
    public class SerieController : Controller
    {
    private readonly ILogger<SerieController> _logger;

    public SerieController(ILogger<SerieController> logger)
    {
        _logger = logger;
    }

        private DataContext db = new DataContext();
        
        [Route("serie")]
        [Route("index")]
        [Route("~/")]

        public IActionResult Index()
        {
            ViewBag.series = db.Series.ToList();
            return View();
        }

        [HttpGet]
        [Route("Add")]
        public IActionResult Add()
        { 
            return View("Add");
        }

        [HttpPost]
        [Route("Add")]
        public IActionResult Add(Serie serie)
        {
            db.Series.Add(serie);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        [Route("Delete/{id}")]
        public IActionResult Delete(string id)
        {
            db.Series.Remove(db.Series.Find(id));
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        [Route("Edite/{id}")]
        public IActionResult Edite(string id)
        {
            return View("Edite", db.Series.Find(id));
        }

        [HttpPost]
        [Route("Edite/{id}")]
        public IActionResult Edite(Serie serie)
        {
            db.Entry(serie).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Privacy()
        {
            return View();
        }
    }
}

Views/Episodio/Add.cshtml
@model VT_POO3.Models.Episodio
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Add</title>
</head>
<body>
    <form method="post" asp-controller="episodio" asp-action="add">
        <table>
            <tr>
                <td>Id</td>
                <td>
                    <input type="text" asp-for="Id" required="required" />
                </td>
            </tr>
            <tr>
                <td>Nome</td>
                <td>
                    <input type="text" asp-for="Nome" required="required" />
                </td>
            </tr>
            <tr>
                <td>Temporada</td>
                <td>
                    <input type="number" asp-for="Temporada" min="0" required="required" />
                </td>
            </tr>
            <tr>
                <td>Nota</td>
                <td>
                    <input type="number" asp-for="Nota" min="0" max="10" required="required" />
                </td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td>
                    <input type="submit" value="Save" />
                </td>
            </tr>
        </table>
    </form>
</body>
</html>

Views/Episodio/Edite.cshtml
@model VT_POO3.Models.Episodio
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edite</title>
</head>
<body>
    <form method="post" asp-controller="episodio" asp-action="edite">
        <table>
            <tr>
                <td>Nome</td>
                <td>
                    <input type="text" asp-for="Nome" required="required" />
                </td>
            </tr>
            <tr>
                <td>Temporada</td>
                <td>
                    <input type="number" asp-for="Temporada" min="0"  required="required" />
                </td>
            </tr>
            <tr>
                <td>Nota</td>
                <td>
                    <input type="number" asp-for="Nota" min="0" max="10"  required="required" />
                </td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td>
                    <input type="submit" value="Save" />
                    <input type="hidden" asp-for="Id" />
                </td>
            </tr>
        </table>
    </form>
</body>
</html>

Views/Episodio/Index_2.cshtml
@model VT_POO3.Models.Episodio

@{
    ViewData["Title"] = "Index_2";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <br>
    <h3>Lista episodios e Adiciona novos ao clicar em "Add episodio"</h3>
    <a asp-controller="episodio" asp-action="add">Add Episodio</a>
    <table border="1" cellpadding="2" cellspacing="2">
        <tr>
            <th>Id</th>
            <th>Nome</th>
            <th>Temporada</th>
            <th>Nota</th>
            <th>Ação</th>
        </tr>
        @foreach (var episodio in ViewBag.episodios)
        {
    <tr>
        <td>@episodio.Id</td>
        <td>@episodio.Nome</td>
        <td>@episodio.Temporada</td>
        <td>@episodio.Nota</td>
        <td>
            <a asp-controller="episodio" asp-action="edite" asp-route-id="@episodio.Id"
               onclick="return confirm('')"> Edite</a>
            <a asp-controller="eposodio" asp-action="delete" asp-route-id="@episodio.Id"
               onclick="return confirm('Voce esta certo disso?')"> Delete</a>
        </td>
    </tr>
        }
    </table>

</body>
</html>

Views/Serie/Add.cshtml
@model VT_POO3.Models.Serie
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Add</title>
</head>
<body>
    <form method="post" asp-controller="serie" asp-action="add">
        <table>
            <tr>
                <td>Id</td>
                <td>
                    <input type="text" asp-for="Id" required="required" />
                </td>
            </tr>
            <tr>
                <td>Nome</td>
                <td>
                    <input type="text" asp-for="Nome" required="required" />
                </td>
            </tr>
            <tr>
                <td>Autor</td>
                <td>
                    <input type="text" asp-for="Autor"  required="required" />
                </td>
            </tr>
            <tr>
                <td>Criadora</td>
                <td>
                    <input type="text" asp-for="Criadora" required="required" />
                </td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td>
                    <input type="submit" value="Save" />
                </td>
            </tr>
        </table>
    </form>
</body>
</html>

Views/Serie/Edite.cshtml
@model VT_POO3.Models.Serie
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edite</title>
</head>
<body>
    <form method="post" asp-controller="serie" asp-action="edite">
        <table>
            <tr>
                <td>Nome</td>
                <td>
                    <input type="text" asp-for="Nome" required="required" />
                </td>
            </tr>
            <tr>
                <td>Autor</td>
                <td>
                    <input type="text" asp-for="Autor"  required="required" />
                </td>
            </tr>
            <tr>
                <td>Criadora</td>
                <td>
                    <input type="text" asp-for="Criadora"  required="required" />
                </td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td>
                    <input type="submit" value="Save" />
                    <input type="hidden" asp-for="Id" />
                </td>
            </tr>
        </table>
    </form>
</body>
</html>

Views/Serie/Index.cshtml
@model VT_POO3.Models.Serie
@{
    ViewData["Title"] = "Home Page";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <h1>Visualizar a explicação do Trabalho na guia "Descrição do trabalho!"</h1>
    <br>
    <h3>Lista séries e adiciona novas ao clicar no link "add series" </h3>
    <a asp-controller="serie" asp-action="add">Add Serie</a>
    <h4>Lista de series click no mome da série e visualize seus episódios</h4>
    <table border="1" cellpadding="2" cellspacing="2">
        <tr>
            <th>Id</th>
            <th>Nome</th>
            <th>Autor</th>
            <th>Criadora</th>
            <th>Ação</th>
        </tr>
        @foreach (var serie in ViewBag.series)
        {
            <tr>
                <td>@serie.Id</td>
                <td>
                    <a asp-controller="episodio" asp-action="Index_2">
                        @serie.Nome
                    </a>
                </td>

                <td>@serie.Autor</td>
                <td>@serie.Criadora</td>
                <td>
                    <a asp-controller="serie" asp-action="edite" asp-route-id="@serie.Id"
                       onclick="return confirm('')"> Edite</a>
                    <a asp-controller="serie" asp-action="delete" asp-route-id="@serie.Id"
                       onclick="return confirm('Voce esta certo disso?')"> Delete</a>
                </td>
            </tr>

        }
    </table>

</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VT_POO3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Serie" asp-action="Index">VT_POO3</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Serie" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">

                            <a class="nav-link text-dark" asp-area="" asp-controller="Serie" asp-action="Privacy">Descrição do Trabalho</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - VT_POO3 - <a asp-area="" asp-controller="Serie" asp-action="Privacy">Descrição do Trabalho</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>